spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facturaciondb
    username: postgres
    password: postgres
#    platform: postgresql

server:
  port: 8002
  
  #configuracion de server de eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
      
#tiempo de respuesta extendido a 5seg 
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      
      
