spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facturaciondb
    username: postgres
    password: postgres
#    platform: postgresql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761//eureka/

server:
  port: 8082
  
